version: "3.8"

services:
  pocketbase:
    build:
      context: ./pocket
      dockerfile: Dockerfile
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pocket/pb_data:/pb_data
    command: ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090"]
